### PR TITLE
Fixes #1153

### LINKED ISSUE #1153: Sorting order is not updated after importing accounts
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.2**
- Platform and version: **Mac 10.13.5**

#### Expected behavior

Account imported should automatically be sorted by the selected preference.

#### Actual behavior

Accounts are imported in the order they are found, and added at the bottom of the list. Changing views doesn't trigger a reorder. The only way to sort correctly the accounts is to manually select the "sort by" option.

#### Steps to reproduce the behavior

- import accounts
- they'll be in the order of importation and not the order of balance

image

### PR DESCRIPTION
**Pull request by gre**
- trigger a reorder on Portfolio page access. 
- trigger reorder in step 4 of add accounts (before AND after)

also don't do a reorder if countervalues are not ready

### Type

polish

### Context

#1153

### Parts of the app affected / Test plan

sorting of accounts

### CODE REVIEW

File: src/components/modals/AddAccounts/steps/04-step-finish.js [hunk 1]
```diff
@@ -30,6 +31,9 @@ const Text = styled(Box).attrs({
 function StepFinish({ currency, t, checkedAccountsIds }: StepProps) {
   return (
     <Box align="center" py={6}>
+      <RefreshAccountsOrdering onMount />
+      {/* the unmount case is useful to trigger a second refresh because most of the time countervalues were not yet loaded... */}
+      <RefreshAccountsOrdering onUnmount />
```
Comment (meriadec) [inline src/components/modals/AddAccounts/steps/04-step-finish.js]: what about having `onMount` and `onUnmount` on the same `RefreshAccountsOrdering`

Comment (gre) [reply src/components/modals/AddAccounts/steps/04-step-finish.js]: aha yeah 😅
