### PR TITLE
remove unwanted cursor pointer to have a more native experience.

### LINKED ISSUE #901: No mouse "pointer" cursor hovering over a content of a button
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0-rc.2
- Platform: macOS

#### Expected behavior

When hovering over a button, mouse cursor should be set as "pointer".

#### Actual behavior

When hovering over a button, mouse cursor is set as "pointer" only when inside button's padding area, but is *not* within button content (icon/text).

#### Steps to reproduce the behavior

Click on image to see the video:

[Reproducing the current issue](https://streamable.com/ff2pw)

### PR DESCRIPTION
**Pull request by valpinkman**
Remove almost all cursor pointer from the app. There are only a few cursor pointers left where the hover state of the element has no UI feedback

fixes #901 

### Type

UI Polish

### Context

Github Issue #901 

### Parts of the app affected / Test plan

All of the parts ;)

### CODE REVIEW

File: src/components/MainSideBar/AddAccountButton.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { rgba } from 'styles/helpers'
 
 const PlusWrapper = styled(Tabbable).attrs({
   p: 1,
-  cursor: 'pointer',
+  cursor: 'default',
```
Comment (meriadec) [inline src/components/MainSideBar/AddAccountButton.js]: `default` is already the default so we can remove the whole line

File: src/components/ManagerPage/AppSearchBar.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ class AppSearchBar extends PureComponent<Props, State> {
           }
           renderRight={
             query ? (
-              <Box justify="center" cursor="pointer" onClick={this.reset} px={3}>
+              <Box justify="center" cursor="text" onClick={this.reset} px={3}>
```
Comment (meriadec) [inline src/components/ManagerPage/AppSearchBar.js]: imo it should be `default` (but it should also have hover state)

File: src/components/Onboarding/index.js [hunk 3]
```diff
@@ -110,7 +110,7 @@ const CloseContainer = styled(Box).attrs({
   p: 4,
   color: 'fog',
 })`
-  cursor: pointer;
+  cursor: initial;
```
Comment (meriadec) [inline src/components/Onboarding/index.js]: remove the line, so it inherit from parent

File: src/components/Onboarding/steps/Finish.js [hunk 4]
```diff
@@ -122,18 +124,19 @@ type SocMed = {
   onClick: string => void,
 }
 
+const StyledBox = styled(Box)`
+  cursor: default;
```
Comment (meriadec) [inline src/components/Onboarding/steps/Finish.js]: already default

File: src/components/Onboarding/steps/Init.js [hunk 5]
```diff
@@ -117,12 +117,12 @@ const InitCardContainer = styled(Box).attrs({
   horizontal: true,
   borderRadius: '4px',
 })`
+  cursor: initial;
```
Comment (meriadec) [inline src/components/Onboarding/steps/Init.js]: already default

File: src/components/Onboarding/steps/SelectDevice.js [hunk 6]
```diff
@@ -95,7 +95,7 @@ const DeviceContainer = styled(Box).attrs({
   height: 204px;
   border: ${props => `1px solid ${props.theme.colors[props.isActive ? 'wallet' : 'fog']}`};
   &:hover {
-    cursor: pointer;
+    cursor: initial;
```
Comment (meriadec) [inline src/components/Onboarding/steps/SelectDevice.js]: remove line

File: src/components/OperationsList/Operation.js [hunk 7]
```diff
@@ -17,7 +17,7 @@ const OperationRow = styled(Box).attrs({
   horizontal: true,
   alignItems: 'center',
 })`
-  cursor: pointer;
+  cursor: initial;
```
Comment (meriadec) [inline src/components/OperationsList/Operation.js]: remove line

File: src/components/TopBar/ItemContainer.js [hunk 8]
```diff
@@ -10,7 +10,7 @@ export default styled(Tabbable).attrs({
   px: 3,
   ml: 0,
   alignItems: 'center',
-  cursor: p => (p.disabled ? 'default' : 'pointer'),
+  cursor: 'default',
```
Comment (meriadec) [inline src/components/TopBar/ItemContainer.js]: remove line (maybe add cursor `not-allowed` if disabled?)
wdyt @khalilbenihoud ?

File: src/components/base/AccountsList/AccountRow.js [hunk 9]
```diff
@@ -121,12 +121,12 @@ const AccountRowContainer = styled(Tabbable).attrs({
 })`
   height: 48px;
   border-radius: 4px;
+  cursor: initial;
```
Comment (meriadec) [inline src/components/base/AccountsList/AccountRow.js]: remove line

File: src/components/base/Button/index.js [hunk 10]
```diff
@@ -168,7 +168,7 @@ const Base = styled.button.attrs({
   ${fontFamily};
   border: none;
   border-radius: ${p => p.theme.radii[1]}px;
-  cursor: ${p => (p.disabled ? 'default' : 'pointer')};
+  cursor: default;
```
Comment (meriadec) [inline src/components/base/Button/index.js]: remove line (or maybe `not-allowed` when disabled)

File: src/components/base/CopyWithFeedback.js [hunk 11]
```diff
@@ -66,10 +66,10 @@ const ClickableWrapper = styled(Box).attrs({
   color: 'wallet',
   fontSize: 4,
   ff: 'Open Sans|SemiBold',
-  cursor: 'pointer',
+  cursor: 'default',
```
Comment (meriadec) [inline src/components/base/CopyWithFeedback.js]: remove line

**Comment by meriadec** [comment]
Oops too late :/

**Comment by gre** [comment]
sorry. yeah maybe @valpinkman  can provide a polish PR :)

File: src/components/MainSideBar/AddAccountButton.js (hunk 1 above)
Comment (valpinkman) [reply src/components/MainSideBar/AddAccountButton.js]: done

File: src/components/ManagerPage/AppSearchBar.js (hunk 2 above)
Comment (valpinkman) [reply src/components/ManagerPage/AppSearchBar.js]: done

File: src/components/Onboarding/index.js (hunk 3 above)
Comment (valpinkman) [reply src/components/Onboarding/index.js]: done

File: src/components/Onboarding/steps/Finish.js (hunk 4 above)
Comment (valpinkman) [reply src/components/Onboarding/steps/Finish.js]: nope, since it's inherited, we have a cursor: text here

File: src/components/Onboarding/steps/Init.js (hunk 5 above)
Comment (valpinkman) [reply src/components/Onboarding/steps/Init.js]: same here, if no default we have a cursor: text

File: src/components/TopBar/ItemContainer.js (hunk 8 above)
Comment (gre) [reply src/components/TopBar/ItemContainer.js]: personally not a big fan of not-allowed cursors. especially on windows if i recall correctly. it's kinda overkill as the UI already show it 🤔

Comment (meriadec) [reply src/components/TopBar/ItemContainer.js]: so if we choose to not use `not-allowed`, we should remove it from side menu item

Comment (valpinkman) [reply src/components/TopBar/ItemContainer.js]: done
