### PR TITLE
Fix a JS bug when you have no txs but have balance

### LINKED ISSUE #1362: ETH Accounts: Cannot match against 'undefined' or 'null'.
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.0
- Platform and version: Mac 10.13.6

#### Expected behavior

When adding an ETH Account, it should find accounts that have only received ETH issued by smart contracts..

#### Actual behavior

Step 3:
- Synchronizing...
- Error: Cannot match against 'undefined' or 'null'.

### PR DESCRIPTION
**Pull request by gre**
+ Fixes #1362 
+ fix visibility of Ethereum wallets that only receive funds from contract

we have to do a patch release this morning

### Type

bug

### Context

#1362

### Parts of the app affected / Test plan

ETH scanning if one of your account have contract-only funds, scan will crash

### CODE REVIEW

File: src/components/modals/AddAccounts/steps/03-step-import.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ import uniq from 'lodash/uniq'
 import { urls } from 'config/urls'
 import ExternalLinkButton from 'components/base/ExternalLinkButton'
 import RetryButton from 'components/base/RetryButton'
+import isAccountEmpty from 'helpers/isAccountEmpty'
```
Comment (meriadec) [inline src/components/modals/AddAccounts/steps/03-step-import.js]: is the file pushed? Don't see it

Comment (gre) [reply src/components/modals/AddAccounts/steps/03-step-import.js]: done
